# db
FROM library/postgres AS DB
USER $USER
ARG DBUSER
ARG DBPWD
ARG DBNAME
ENV POSTGRES_USER=$DBUSER
ENV POSTGRES_PASSWORD=$DBPWD
ENV POSTGRES_DB=$DBNAME
RUN echo "POSTGRES_USER = $POSTGRES_USER"
RUN echo "POSTGRES_PASSWORD = $POSTGRES_PASSWORD"

# app
FROM camunda/camunda-bpm-platform:latest AS APP
USER $USER
ARG DBUSER
ARG DBPWD
ARG DBNAME
ENV DB_DRIVER=org.postgresql.Driver
ENV DB_URL=jdbc:postgresql://db:5432/$DBNAME
ENV DB_USERNAME=$DBUSER
ENV DB_PASSWORD=$DBPWD
ENV WAIT_FOR=db:5432
RUN echo "DB_USER = ${DB_USERNAME}"
RUN echo "DB_PASSWORD = ${DB_PASSWORD}"
RUN echo "DB_URL = ${DB_URL}"
